[package]
name = "chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
chess-core = { path = "../chess_core" }
eframe = "0.33"
egui = "0.33"
resvg = "0.46.0"
usvg = "0.46.0"
tiny-skia = "0.11.4"